# This is a basic workflow to help you get started with Actions

name: 生成exe

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: PyInstaller Windows
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      	uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          # Directory containing source code (optional requirements.txt).
          path: # default is src
          # Specify a custom URL for PYPI
          pypi_url: # optional, default is https://pypi.python.org/
          # Specify a custom URL for PYPI Index
          pypi_index_url: # optional, default is https://pypi.python.org/simple
          # Specify a file path for .spec file
          spec: # optional, default is 
