# This is a basic workflow to help you get started with Actions

name: Auto-Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: 0 0 1 * *
  # Allows you to run this workflow manually from the Actions tab
  push:
    tags:
      - "*.*.*"

  workflow_dispatch:
    inputs:
      version:
        description: "版本号"
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-Windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Set environment variables for UTF-8 encoding
    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: "3.13"

      # Runs a single command using the runners shell
      - name: Install pip
        run: pip install -r requirements.txt
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.6
      # Runs a set of commands using the runners shell
      - name: flet
        run: |
          $env:PYTHONIOENCODING="utf-8"
          flet build windows -v
      # ren ./build/HT_Music_Downloader.exe "HT-Music-Downloader-Windows.exe"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: HT-Music-Downloader-Windows
          # A file, directory or wildcard pattern that describes what to upload
          path: build/windows

  build-MacOS:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Set environment variables for UTF-8 encoding
    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: "3.13"

      # Runs a single command using the runners shell
      - name: Install pip
        run: |
          export PYTHONIOENCODING=utf-8
          pip install -r requirements.txt
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.6
      # Runs a set of commands using the runners shell
      - name: flet
        run: |
          export PYTHONIOENCODING=utf-8
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          flet build macos -v
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: HT-Music-Downloader-MacOS
          # A file, directory or wildcard pattern that describes what to upload
          path: build/macos

  build-Linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: "3.13"

      # Install GTK 3.0 development libraries
      - name: Install GTK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libglib2.0-dev libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev libatk1.0-dev
          sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      # Runs a single command using the runners shell
      - name: Install pip
        run: pip install -r requirements.txt
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.6
      # Runs a set of commands using the runners shell
      - name: flet
        run: flet build linux -v
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: HT-Music-Downloader-Linux
          # A file, directory or wildcard pattern that describes what to upload
          path: build/linux

  # build-Android:
  #   # The type of runner that the job will run on
  #   runs-on: windows-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3

  #     - name: Setup Python
  #       uses: actions/setup-python@v4.1.0
  #       with:
  #         # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
  #         python-version: '3.11'

  #     # Runs a single command using the runners shell
  #     - name: Install pip
  #       run: pip install -r requirements.txt
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #         flutter-version: 3.19.6
  #     # Runs a set of commands using the runners shell
  #     - name: flet
  #       run: |
  #         flet build apk --module-name HT_Music_Downloader.py --include-packages flet_audio
  #         zip -r HT-Music-Downloader-Android.zip build/apk/
  #     - name: Upload a Build Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         # Artifact name
  #         name: HT-Music-Downloader-Android
  #         # A file, directory or wildcard pattern that describes what to upload
  #         path: HT-Music-Downloader-Android.zip

  Auto_release:
    needs: [build-Windows, build-MacOS, build-Linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: HT-Music-Downloader-Linux
          path: ./
      - uses: vimtor/action-zip@v1
        with:
          files: HT-Music-Downloader-Linux
          dest: HT-Music-Downloader-Linux.zip

      - uses: actions/download-artifact@v4
        with:
          name: HT-Music-Downloader-MacOS
          path: ./
      - uses: vimtor/action-zip@v1
        with:
          files: HT-Music-Downloader-MacOS
          dest: HT-Music-Downloader-MacOS.zip

      - uses: actions/download-artifact@v4
        with:
          name: HT-Music-Downloader-Windows
          path: ./
      - uses: vimtor/action-zip@v1
        with:
          files: HT-Music-Downloader-Windows
          dest: HT-Music-Downloader-Windows.zip

      #  - uses: actions/download-artifact@v4
      #    with:
      #     name: HT-Music-Downloader-Android
      #     path: ./

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name=='workflow_dispatch'
        with:
          tag_name: "${{ github.event.inputs.version }}"
          # Should this release be marked as a draft?
          draft: false
          generate_release_notes: true
          # Should this release be marked as a pre-release?
          prerelease: true # optional, default is true
          # Release title (for automatic releases)
          name: "${{ github.event.inputs.version }} - CI"
          # Assets to upload to the release
          files: |
            *.zip
