# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "flet-v4" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.1.0

      # Runs a single command using the runners shell
      - name: Install pip
        run: pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Pyinstaller
        run: |
          pyinstaller -F init.py -i icon.ico --add-data "assets;assets"
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # GitHub secret token
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          # Should this release be marked as a draft?
          draft: true
          # Should this release be marked as a pre-release?
          prerelease: true # optional, default is true
          # Release title (for automatic releases)
          title: 自动构建
          # Assets to upload to the release
          files: ./dist

